### ISSUE TITLE
为什么遇360就秒退呢？

### ISSUE THREAD

**Issue by OCTSJimmy** [miaomiaosoft/Acrylic-DNS-Proxy-GUI#19]
为什么遇360就秒退呢？完全可以给个提示，我给360手动加白名单嘛……
作者大大，能不能求您不要遇到360就秒退……

**Comment by miaomiaosoft** [comment]
重新下载：https://github.com/miaomiaosoft/Acrylic-DNS-Proxy-GUI/releases/tag/5.0

将config.ini文件内的360项的数值改为0将不检测！
