### ISSUE TITLE
english support?

### ISSUE THREAD

**Issue by msenturk** [miaomiaosoft/Acrylic-DNS-Proxy-GUI#2]

**Comment by miaomiaosoft** [comment]
Sorry, can not available in English.

It was originally the English project, here: http: //mayakron.altervista.org/wikibase/show.php id = AcrylicHome?

GUI procedure is added to a special Chinese network, so if you are not living in China, then you can directly use the English project!

**Comment by msenturk** [comment]
thx for info. I'm just interesting with english gui part.
