### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by PHizing** [miaomiaosoft/Acrylic-DNS-Proxy-GUI#4]
点击GUI上的有关于启动服务，停止服务，重启服务等按钮，没有一点反应。
win7 64位的环境。GUI 3.5.2。

**Comment by miaomiaosoft** [comment]
我也是同样的系统  但是没有任何问题
请保持文件路径纯英文
使用管理员权限启动

**Comment by PHizing** [comment]
是英文路径，也是管理员方式启动。
是不是这个服务还需要依赖其它服务啊？

**Comment by miaomiaosoft** [comment]
不需要   如果实在不行可以留下QQ  远程帮你看看

**Comment by PHizing** [comment]
我家里的机器，到时候联络你。

**Comment by PHizing** [comment]
已经好了，问题关闭。
